#define PRODUCT_NAME			"AiSec"
#define PRODUCT_VERSION			"9.24.2"
#define PRODUCT_VERSION_RESOURCE	9,24,2,601
#define PRODUCT_TAP_WIN_COMPONENT_ID	"tap0901"
#define PRODUCT_TAP_WIN_MAJOR		9
#define PRODUCT_TAP_WIN_MINOR		24
#define PRODUCT_TAP_WIN_PROVIDER		"AiSec Provider V9"
#define PRODUCT_TAP_WIN_DEVICE_DESCRIPTION	"AiSec Adapter V9"
#define PRODUCT_TAP_WIN_RELDATE		"09/27/2019"
#define PRODUCT_TAP_WIN_REVISION	2
#define PRODUCT_TAP_WIN_BUILD		601
